[build-system]
requires = ["setuptools>=67", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "op-observe"
version = "0.1.0"
description = "Telemetry integration for OP-Observe"
readme = "README.md"
authors = [{name = "OP-Observe"}]
requires-python = ">=3.10"
dependencies = [
    "opentelemetry-api>=1.22.0",
    "opentelemetry-sdk>=1.22.0",
    "opentelemetry-exporter-otlp-proto-http>=1.22.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.1.1",
    "pytest-cov>=4.1.0",
]

[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-ra"
markers = [
    "integration: marks tests that spin up docker-compose environments",
]
