[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "op-observe"
version = "0.1.0"
description = "Environment, secrets, and RBAC utilities for OP-Observe"
readme = "README.md"
requires-python = ">=3.10"
authors = [{name = "OP-Observe Maintainers"}]
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest>=7.4",
]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra"
testpaths = ["tests"]
