[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "op-observe"
version = "0.1.0"
description = "Golden templates for OP-Observe demos"
authors = [{name = "OP Observe", email = "maintainers@example.com"}]
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

