[build-system]
requires = ["setuptools>=67", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "op-observe-security"
version = "0.1.0"
description = "Security reporting utilities for the OP-Observe CI pipeline"
authors = [{name = "OP-Observe Maintainers"}]
requires-python = ">=3.11"
dependencies = []

[project.optional-dependencies]
dev = ["pytest>=7.4"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
